"""Remotion tutorial video renderer.

Video sources are JSON *composition specs*::

    {
      "title": "Getting started",
      "fps": 30,
      "width": 1920,
      "height": 1080,
      "scenes": [
        {"heading": "Sign in", "body": "Open the app and ...",
         "duration_seconds": 4}
      ]
    }

Rendering a real MP4 requires Node.js, so this renderer has two modes:

- ``bundle`` (default): emit a complete, ready-to-render Remotion project
  as a deterministic ZIP archive.  Any machine with Node can unzip it and
  run ``npm install && npx remotion render`` -- including a CI job.
- ``video``: scaffold the same project into the workspace and invoke the
  Remotion CLI directly, returning MP4 bytes.  Requires ``npx`` on PATH.

Select the mode with ``options={"mode": "video"}``.
"""

from __future__ import annotations

import io
import json
import shutil
import subprocess
import zipfile
from pathlib import Path
from typing import Any, ClassVar

from narrate.exceptions import RenderError
from narrate.models import ArtifactKind
from narrate.rendering.base import Renderer, RenderRequest, RenderResult

__all__ = ["RemotionRenderer"]

_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)

_PACKAGE_JSON = {
    "name": "narrate-video",
    "private": True,
    "scripts": {
        "render": "remotion render src/index.ts NarrateVideo out/video.mp4 --props=props.json",
    },
    "dependencies": {
        "@remotion/cli": "^4.0.0",
        "react": "^18.3.0",
        "react-dom": "^18.3.0",
        "remotion": "^4.0.0",
    },
    "devDependencies": {
        "@types/react": "^18.3.0",
        "typescript": "^5.5.0",
    },
}

_TSCONFIG = {
    "compilerOptions": {
        "target": "ES2022",
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "jsx": "react-jsx",
        "strict": True,
        "skipLibCheck": True,
    },
    "include": ["src"],
}

_INDEX_TS = """import {registerRoot} from 'remotion';
import {Root} from './Root';

registerRoot(Root);
"""

_ROOT_TSX = """import {Composition, getInputProps} from 'remotion';
import {NarrateVideo, VideoProps, totalFrames} from './NarrateVideo';

export const Root: React.FC = () => {
  const props = getInputProps() as unknown as VideoProps;
  return (
    <Composition
      id="NarrateVideo"
      component={NarrateVideo}
      durationInFrames={totalFrames(props)}
      fps={props.fps}
      width={props.width}
      height={props.height}
      defaultProps={props}
    />
  );
};
"""

_VIDEO_TSX = """import {AbsoluteFill, Sequence, interpolate, useCurrentFrame} from 'remotion';

export type Scene = {heading: string; body: string; duration_seconds: number};
export type VideoProps = {
  title: string;
  fps: number;
  width: number;
  height: number;
  scenes: Scene[];
};

export const totalFrames = (props: VideoProps): number =>
  Math.max(
    1,
    props.scenes.reduce((sum, scene) => sum + Math.round(scene.duration_seconds * props.fps), 0),
  );

const SceneCard: React.FC<{scene: Scene; fps: number}> = ({scene, fps}) => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, fps / 2], [0, 1], {extrapolateRight: 'clamp'});
  return (
    <AbsoluteFill
      style={{
        backgroundColor: '#111827',
        color: '#f9fafb',
        justifyContent: 'center',
        padding: '10%',
        fontFamily: 'Helvetica, Arial, sans-serif',
        opacity,
      }}
    >
      <h1 style={{fontSize: 72, marginBottom: 24}}>{scene.heading}</h1>
      <p style={{fontSize: 36, lineHeight: 1.5, color: '#d1d5db'}}>{scene.body}</p>
    </AbsoluteFill>
  );
};

export const NarrateVideo: React.FC<VideoProps> = (props) => {
  let cursor = 0;
  return (
    <AbsoluteFill>
      {props.scenes.map((scene, index) => {
        const durationInFrames = Math.round(scene.duration_seconds * props.fps);
        const from = cursor;
        cursor += durationInFrames;
        return (
          <Sequence key={index} from={from} durationInFrames={durationInFrames}>
            <SceneCard scene={scene} fps={props.fps} />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
"""

_README = """# Narrate video bundle

This is a ready-to-render [Remotion](https://www.remotion.dev) project
generated by Narrate.  To produce the MP4:

    npm install
    npm run render

The output lands in `out/video.mp4`.  Composition data lives in
`props.json`; edit it and re-render to iterate.
"""


class RemotionRenderer(Renderer):
    """Render video composition specs via Remotion."""

    name: ClassVar[str] = "remotion_video"
    input_kinds: ClassVar[frozenset[ArtifactKind]] = frozenset({ArtifactKind.VIDEO})
    output_kind: ClassVar[ArtifactKind] = ArtifactKind.VIDEO
    description: ClassVar[str] = "Render tutorial videos with Remotion (bundle or MP4)"

    def render(self, request: RenderRequest) -> RenderResult:
        """Produce a render bundle ZIP or an MP4.

        Raises:
            RenderError: If the composition spec is malformed, the mode
                is unknown, or (in ``video`` mode) the Remotion CLI is
                unavailable or fails.
        """
        self.check_input(request)
        spec = self._validate_spec(request.json())
        mode = str(request.options.get("mode", "bundle"))
        if mode == "bundle":
            return self._render_bundle(spec)
        if mode == "video":
            return self._render_video(spec, request.workspace, request.artifact.id)
        msg = f"unknown remotion mode {mode!r} (use 'bundle' or 'video')"
        raise RenderError(msg)

    @staticmethod
    def _validate_spec(document: Any) -> dict[str, Any]:  # noqa: ANN401 - JSON input
        if not isinstance(document, dict):
            msg = "video source must be a JSON object"
            raise RenderError(msg)
        scenes = document.get("scenes")
        if not isinstance(scenes, list) or not scenes:
            msg = 'video source needs a non-empty "scenes" array'
            raise RenderError(msg)
        scene_list: list[Any] = scenes
        for index, scene in enumerate(scene_list):
            if not isinstance(scene, dict) or "heading" not in scene:
                msg = f'scene {index} must be an object with a "heading"'
                raise RenderError(msg)
            duration = scene.get("duration_seconds", 4)
            if not isinstance(duration, int | float) or duration <= 0:
                msg = f"scene {index} needs a positive duration_seconds"
                raise RenderError(msg)
        return {
            "title": str(document.get("title", "Narrate video")),
            "fps": int(document.get("fps", 30)),
            "width": int(document.get("width", 1920)),
            "height": int(document.get("height", 1080)),
            "scenes": [
                {
                    "heading": str(scene["heading"]),
                    "body": str(scene.get("body", "")),
                    "duration_seconds": float(scene.get("duration_seconds", 4)),
                }
                for scene in scene_list
            ],
        }

    @classmethod
    def _project_files(cls, spec: dict[str, Any]) -> dict[str, str]:
        """Return the full Remotion project as ``{relative_path: content}``."""
        return {
            "package.json": json.dumps(_PACKAGE_JSON, indent=2) + "\n",
            "tsconfig.json": json.dumps(_TSCONFIG, indent=2) + "\n",
            "props.json": json.dumps(spec, indent=2) + "\n",
            "src/index.ts": _INDEX_TS,
            "src/Root.tsx": _ROOT_TSX,
            "src/NarrateVideo.tsx": _VIDEO_TSX,
            "README.md": _README,
        }

    @classmethod
    def _render_bundle(cls, spec: dict[str, Any]) -> RenderResult:
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for path, content in sorted(cls._project_files(spec).items()):
                info = zipfile.ZipInfo(path, date_time=_ZIP_EPOCH)
                info.external_attr = 0o644 << 16
                archive.writestr(info, content)
        total_seconds = sum(scene["duration_seconds"] for scene in spec["scenes"])
        return RenderResult(
            content=buffer.getvalue(),
            kind=ArtifactKind.VIDEO,
            media_type="application/zip",
            suffix=".remotion.zip",
            metadata={
                "mode": "bundle",
                "scenes": len(spec["scenes"]),
                "duration_seconds": total_seconds,
                "render_command": "npm install && npm run render",
            },
        )

    @classmethod
    def _render_video(cls, spec: dict[str, Any], workspace: Path, artifact_id: str) -> RenderResult:
        npx = shutil.which("npx")
        npm = shutil.which("npm")
        if npx is None or npm is None:
            msg = (
                "remotion 'video' mode requires Node.js (npm and npx on PATH); "
                "use mode='bundle' to get a portable render bundle instead"
            )
            raise RenderError(msg)

        project_dir = workspace / f"remotion-{artifact_id}"
        for path, content in cls._project_files(spec).items():
            target = project_dir / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

        output = project_dir / "out" / "video.mp4"
        for command in ([npm, "install", "--no-audit", "--no-fund"], [npm, "run", "render"]):
            completed = subprocess.run(
                command,
                cwd=project_dir,
                capture_output=True,
                text=True,
                check=False,
            )
            if completed.returncode != 0:
                msg = (
                    f"remotion command {' '.join(command)!r} failed "
                    f"({completed.returncode}): {completed.stderr[-2000:]}"
                )
                raise RenderError(msg)
        if not output.exists():
            msg = "remotion render completed but produced no out/video.mp4"
            raise RenderError(msg)
        total_seconds = sum(scene["duration_seconds"] for scene in spec["scenes"])
        return RenderResult(
            content=output.read_bytes(),
            kind=ArtifactKind.VIDEO,
            media_type="video/mp4",
            suffix=".mp4",
            metadata={
                "mode": "video",
                "scenes": len(spec["scenes"]),
                "duration_seconds": total_seconds,
            },
        )
